name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🚀 بدء عملية النشر..."
            cd ${{ secrets.DEPLOY_PATH }}
            
            # سحب التحديثات
            git fetch --all
            git reset --hard origin/master
            
            # تثبيت dependencies
            composer install --no-dev --optimize-autoloader
            
            # صلاحيات Laravel
            chmod -R 775 storage bootstrap/cache
            
            # تنظيف الكاش
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            #Storage
            rm -rf public/storage
            php artisan storage:link
            
            # صلاحيات الملفات
            find . -type f -exec chmod 644 {} \;
            find . -type d -exec chmod 755 {} \;
            
            echo "✅ تم النشر بنجاح!"
